### ISSUE TITLE
Random failure during subscribing to /amq/queue. 

### ISSUE THREAD

**Issue by rgeorgiev** [rabbitmq/rabbitmq-stomp#14] opened 2015-06-08 19:44 UTC
It look like a concurrency issue, as it happens when two subscriptions happen on the same time.
Here are the Rabbit log at the time of error:

```
=ERROR REPORT==== 8-Jun-2015::18:00:33 ===
Channel error on connection <0.283.0> (127.0.0.1:43154 -> 127.0.0.1:5671, vhost: '/', user: 'vcac-server_26325'), channel 6:
{amqp_error,not_found,
            "no queue 'ebs.testSubscribeAsSystemAdmin.serviceTypeId1.eventTopic.one0.testSubscribeAsSystemAdmin0' in vhost '/'",
            'queue.declare'}

=INFO REPORT==== 8-Jun-2015::18:00:33 ===
accepting STOMP connection <0.1506.0> (127.0.0.1:40240 -> 127.0.0.1:61613)

=ERROR REPORT==== 8-Jun-2015::18:00:34 ===
connection <0.1509.0>, channel 1 - error:
{amqp_error,not_allowed,
            "attempt to reuse consumer tag 'T_testSubscribeAsSystemAdmin0'",
            'basic.consume'}

=WARNING REPORT==== 8-Jun-2015::18:00:34 ===
Connection (<0.1509.0>) closing: received hard error {server_initiated_close,
                                                      530,
                                                      "attempt to reuse consumer tag 'T_testSubscribeAsSystemAdmin0'"} from server

=ERROR REPORT==== 8-Jun-2015::18:00:34 ===
STOMP error frame sent:
Message: "Processing error"
Detail: "Processing error"
Server private detail: {{shutdown,
                            {connection_closing,
                                {server_initiated_close,530,
                                    "attempt to reuse consumer tag 'T_testSubscribeAsSystemAdmin0'"}}},
                        {gen_server,call,
                            [<0.1515.0>,
                             {subscribe,
                                 {'basic.consume',0,
                                     <<"ebs.testSubscribeAsSystemAdmin.serviceTypeId1.eventTopic.one0.testSubscribeAsSystemAdmin0">>,
                                     <<"T_testSubscribeAsSystemAdmin0">>,
                                     false,true,false,false,[]},
                                 <0.1505.0>},
                             infinity]}}

=ERROR REPORT==== 8-Jun-2015::18:00:34 ===
** Generic server <0.1505.0> terminating
** Last message in was {'EXIT',<0.1515.0>,
                           {shutdown,
                               {connection_closing,
                                   {server_initiated_close,530,
                                       "attempt to reuse consumer tag 'T_testSubscribeAsSystemAdmin0'"}}}}
** When Server state == {state,"session-pXXzcqyPuT4rZsCCbAUJ9Q",<0.1515.0>,
                         <0.1509.0>,
                         {dict,1,16,16,8,80,48,
                          {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},
                          {{[],[],[],[],[],[],[],[],
                            [[<<"T_testSubscribeAsSystemAdmin0">>|
                              {subscription,
                               "/amq/queue/ebs.testSubscribeAsSystemAdmin.serviceTypeId1.eventTopic.one0.testSubscribeAsSystemAdmin0",
                               auto,false,
                               "id='testSubscribeAsSystemAdmin0'"}]],
                            [],[],[],[],[],[],[]}}},
                         "1.2",#Fun<rabbit_stomp_reader.1.50399846>,undefined,
                         {stomp_configuration,"guest","guest",false,false},
                         {set,0,16,16,8,80,48,
                          {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},
                          {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}},
                         {dict,0,16,16,8,80,48,
                          {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},
                          {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}},
                         #Fun<rabbit_stomp_processor.5.63782375>,
                         {amqp_adapter_info,
                          {0,0,0,0,0,65535,32512,1},
                          61613,
                          {0,0,0,0,0,65535,32512,1},
                          40240,<<"127.0.0.1:40240 -> 127.0.0.1:61613">>,
                          {'STOMP',0},
                          [{ssl,false}]},
                         #Fun<rabbit_stomp_reader.0.22944995>,none,
                         {0,0,0,0,0,65535,32512,1}}
** Reason for termination == 
** {channel_died,
       {shutdown,
           {connection_closing,
               {server_initiated_close,530,
                   "attempt to reuse consumer tag 'T_testSubscribeAsSystemAdmin0'"}}}}

=INFO REPORT==== 8-Jun-2015::18:00:34 ===
closing STOMP connection <0.1506.0> (127.0.0.1:40240 -> 127.0.0.1:61613)
```

**Comment by michaelklishin** [comment] 2015-06-08 19:47
Yes, looks like it.

**Comment by videlalvaro** [comment] 2015-09-10 09:36
One of the errors say:

```erlang
connection <0.1509.0>, channel 1 - error:
{amqp_error,not_allowed,
            "attempt to reuse consumer tag 'T_testSubscribeAsSystemAdmin0'",
            'basic.consume'}
```

Consumer tags in AMQP are either server generated (by RabbitMQ) or sent by the client. If a consumer tag is being reused, it means the client is generating those names, not the broker. In our case, this means the STOMP plugin is generating said tag.

Looking at `rabbit_stomp_processor.erl` we can see that the variable `ConsumerTag` is used all over the place in that code. So it is indeed generated by the STOMP processor, and then used for the various `basic.consume`, `basic.cancel`, and related AMQP calls.

New subscriptions are kept on a `dict` as seen here: https://github.com/rabbitmq/rabbitmq-stomp/blob/master/src/rabbit_stomp_processor.erl#L622 where the `ConsumerTag` is the key on that dict. Seeing where Conusmer tags are added and removed from that dict might help you find what code inside the STOMP processor is not handling errors, leaving ConsumerTags behind.

For example this code here: https://github.com/rabbitmq/rabbitmq-stomp/blob/master/src/rabbit_stomp_processor.erl#L442 erases the `ConsumerTag` from the dict. Perhaps is not called all the time?

**Comment by michaelklishin** [comment] 2015-09-10 09:38
Or the tag is client-provided and we don't account for possible duplicates.

**Comment by videlalvaro** [comment] 2015-09-10 09:40
It seems to be auto-generated here https://github.com/rabbitmq/rabbitmq-stomp/blob/master/src/rabbit_stomp_processor.erl#L589 based on the STOMP frame

**Comment by videlalvaro** [comment] 2015-09-10 10:04
Furthermore, the consumer tag in question has this format: `'T_testSubscribeAsSystemAdmin0'`

That `T_` prefix is delcared here: https://github.com/rabbitmq/rabbitmq-stomp/blob/master/src/rabbit_stomp_util.erl#L32 `-define(INTERNAL_TAG_PREFIX, "T_").`

Which is only used here for generating a tag: https://github.com/rabbitmq/rabbitmq-stomp/blob/master/src/rabbit_stomp_util.erl#L249 The function `internal_tag` is not exported, so it has to be used inside that module. 

Now, `internal_tag` is called here https://github.com/rabbitmq/rabbitmq-stomp/blob/master/src/rabbit_stomp_util.erl#L40 and here: https://github.com/rabbitmq/rabbitmq-stomp/blob/master/src/rabbit_stomp_util.erl#L46

In the first case the `?TEMP_QUEUE_ID_PREFIX` constant is prepended to the `QueueId` which rules this usage out, since `-define(TEMP_QUEUE_ID_PREFIX, "/temp-queue/").` and we don't see ` "/temp-queue/"` in the error log `ConsumerTag`.

This leave us with the usage here: https://github.com/rabbitmq/rabbitmq-stomp/blob/master/src/rabbit_stomp_util.erl#L46 which brings us back to this line here: https://github.com/rabbitmq/rabbitmq-stomp/blob/master/src/rabbit_stomp_processor.erl#L589 since the error happens at `basic.consume`. 

Note that the other use of `rabbit_stomp_util:consumer_tag/1` is here https://github.com/rabbitmq/rabbitmq-stomp/blob/master/src/rabbit_stomp_processor.erl#L305 but that's an `UNSUBSCRIBE` frame.

**Comment by videlalvaro** [comment] 2015-09-10 14:51
I've managed to reproduce the error by sending the following frames:

https://gist.github.com/videlalvaro/d9243a03d7cfc38c6351

**Comment by priviterag** [comment] 2015-09-11 16:19
checked  what Apollo does in case of duplicated consumer id (http://svn.apache.org/repos/asf/activemq/activemq-apollo/trunk/apollo-stomp/src/main/scala/org/apache/activemq/apollo/stomp/StompProtocolHandler.scala on_stomp_subscribe & die functions):
1) it sends an ERROR frame 
2) disconnect the consumer

**Comment by michaelklishin** [comment] 2015-09-11 16:26
I suggest that we do the same thing.

**Comment by michaelklishin** [comment] 2015-09-16 16:00
We believe this is fixed by https://github.com/rabbitmq/rabbitmq-stomp/pull/35, will be in `3.5.5`.

**Closed by michaelklishin** 2015-09-16 16:00 UTC
Labels: bug, effort-low

**Comment by michaelklishin** [comment] 2015-09-16 22:48
Milestone: n/a because this is a duplicate of #5.
